name: williamlee
favicon: null
layout_spectrum: 0.23254420794546604
typography_spectrum: 0.026334167923778296
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6390253868885338
  lightness: 0.5888093702960759
  saturation: 0.3507316706236452
  rhythmicContrast: 0.7024900342803448
purpose: []
